mysite/UHRS/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include("project.urls")),
    url(r'^admin/', admin.site.urls),
]

mysite/project/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^project/$', views.project_index, name='project_index'),
    url(r'^project/new/$', views.project_new, name='project_new'),
    url(r'^project/task_view/example/(?P<task_view_id>[0-9]+)/', views.project_example, name='project_example'),
    url(r'^project/(?P<project_id>[0-9]+)/$', views.project_summary, name='project_summary'),
    url(r'^project/(?P<project_id>[0-9]+)/(?P<user_id>[0-9]+)/task/$', views.project_task, name='project_task'),
    url(r'^project/(?P<project_id>[0-9]+)/result/$', views.project_result, name='project_result'),
    url(r'^project/(?P<project_id>[0-9]+)/result_details/$', views.project_result_details, name='project_result_details'),
    url(r'^project/(?P<project_id>[0-9]+)/(?P<user_id>[0-9]+)/(?P<data_id>[0-9]+)/answer/$', views.project_answer, name='project_answer'),

    # urls below are for transvote

    url(r'^polls/$', views.transvote_index, name='transvote_index'),
    url(r'^polls/search/$', views.transvote_search, name='transvote_search'),
    url(r'^polls/(?P<voteresult_id>[0-9]+)/$', views.transvote_vote, name='transvote_vote'),
    url(r'^polls/result/(?P<voteresult_id>[0-9]+)/$', views.transvote_result, name='transvote_result'),
    url(r'^polls/download/$', views.transvote_download, name='transvote_download'),
]

mysite/project/models.py
from django.db import models

"""
Upon this point, all models are used for Project APP
"""


class Source(models.Model):
    name = models.CharField(max_length=256)
    create_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Data(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    json = models.TextField()

    def __str__(self):
        return "%r, %r" % (self.source, self.json)


class TaskView(models.Model):
    name = models.CharField(max_length=256)
    javascript = models.TextField()
    html = models.TextField()
    data_example = models.TextField(null=True, blank=True, default=None)
    create_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class User(models.Model):
    name = models.CharField(max_length=256)
    email = models.EmailField()

    # user_boundary = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=256)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    task_view = models.ForeignKey(TaskView, on_delete=models.CASCADE)
    project_type = models.CharField(max_length=64)
    users = models.ManyToManyField(User)
    create_time = models.DateTimeField(auto_now=True)
    result_details_view = models.CharField(max_length=256, null=True, blank=True, default=None)
    project_boundary = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Result(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
    data = models.ForeignKey(Data, on_delete=models.CASCADE)
    result = models.CharField(max_length=4096, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    create_time = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'data', 'project')

    def __str__(self):
        return "%r, %r, %r, %r" % (self.project, self.user, self.data, self.result)


"""
Upon this point, all models are used for Project APP
"""


class TransSource(models.Model):
    trans_source = models.TextField(null=True)
    trans_source_lang = models.CharField(max_length=2, null=True)
    # trans_source_type = models.CharField(max_length=2, null=True)
    trans_output_lang = models.CharField(max_length=2, null=True)

    def __str__(self):
        return self.trans_source


class TransResult(models.Model):
    trans_source = models.ForeignKey(TransSource, null=True, on_delete=models.CASCADE)
    trans_engine = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.trans_engine


class TransHistory(models.Model):
    trans_result = models.ForeignKey(TransResult, null=True, on_delete=models.CASCADE)
    trans_content = models.TextField(null=True)
    trans_time = models.DateTimeField(null=True, blank=True)
    vote_result = models.IntegerField(default=0)
    vote_time = models.DateTimeField(null=True, blank=True)
    bogus_score = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.trans_content


class TransUser(models.Model):
    trans_his = models.ForeignKey(TransHistory, null=True, on_delete=models.CASCADE)
    score = models.CharField(max_length=100, null=True)
    user_trans = models.TextField(null=True)

    def __str__(self):
        return self.user_trans


class Comment(models.Model):
    trans_his = models.ForeignKey(TransHistory, null=True, on_delete=models.CASCADE)
    comment = models.TextField(null=True)

    def __str__(self):
        return self.comment

mysite/project/views.py
import json
from math import ceil

from django.db.models import Count
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect

from .models import Project, User, Result, Data, Source, TaskView

'''
Package only used for TransVote APP are shown below
'''

import queue
import os
import threading
import shlex
import requests
import datetime
import random
import subprocess
from django.utils import timezone
from django.contrib import messages
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from .models import TransSource, TransResult, TransHistory, TransUser


PROJECT_TYPE_ALL = 'ALL'
PROJECT_TYPE_DISTRIBUTE = "DISTRIBUTE"


def homepage(request):
    return render(request, 'homepage.html')


"""
Upon this point, all functions are used for Project APP
"""


def project_index(request):
    '''
    Index page.
    '''
    project_list_in = Project.objects.order_by('-create_time').all()
    paginator = Paginator(project_list_in, 10)  # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        project_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        project_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        project_list = paginator.page(paginator.num_pages)
    return render(request, 'project/project_list.html', {'project_list': project_list})


def project_summary(request, project_id):
    '''
    Summary page for a project.
    '''
    project = get_object_or_404(Project, pk=project_id)
    users_stat = []
    for user in project.users.all():
        users_stat.append({"name": user.name, "id": user.id, "finished": user.result_set.filter(project=project,
                                                                                                result__isnull=False).count()})
    return render(request, 'project/project_summary.html', {'project': project, "users_stat": users_stat})


def project_task(request, project_id, user_id):
    '''
    Task page for an user on a project.
    '''
    project = get_object_or_404(Project, pk=project_id)
    user = get_object_or_404(User, pk=user_id)
    print("user_id: %s, project_id: %s" % (user_id, project_id))
    data = None
    if project.project_type == PROJECT_TYPE_ALL:
        data_id_boundary = 0
        try:
            result = Result.objects.filter(user=user, project=project).order_by('-data')[0]
            data_id_boundary = result.data.id
        except IndexError:
            pass

        try:
            data = project.source.data_set.filter(id__gt = data_id_boundary)[0]
        except IndexError:
            return render(request, 'project/task_completion.html', {'project': project, 'user': user})
    elif project.project_type == PROJECT_TYPE_DISTRIBUTE:
        try:
            selected_choice = Result.objects.raw(
                " select * from project_result where project_id = %s and user_id = %s "
                " and result is null", [str(project_id), str(user_id)]
            )[0]
        except IndexError:
            return render(request, 'project/task_completion.html', {'project': project, 'user': user})
        data = selected_choice.data
    else:
        return HttpResponse('Unknow project type:' + project.project_type)

    finished=user.result_set.filter(project=project).count()
    return render(request,
        'project/task.html',
        {'project': project, 'task_view': project.task_view, 'user': user, 'data': data, 'finished': finished})


def project_result(request, project_id):
    '''
    Result page for a project. This page only displays a summary informaiton.
    '''
    project = get_object_or_404(Project, pk=project_id)
    project_result = Result.objects.filter(project=project)
    user_agg_result = project_result.values("result", "user__name").annotate(result_count=Count('result')).order_by("user__name")
    template_name = "default_result"
    if 'template_name' in request.GET and request.GET['template_name'] != "None":
        template_name = request.GET['template_name']
    return render(request,
        'project/result/%s.html' % template_name,
        {'user_agg_result': user_agg_result})


def project_result_details(request, project_id):
    '''
    Result details page for a project.
    '''

    template_name = "default_result_details"
    if 'template_name' in request.GET and request.GET['template_name'] != "None":
        template_name = request.GET['template_name']

    if template_name == "default_result_details":
        project = get_object_or_404(Project, pk=project_id)
        project_result = Result.objects.filter(project=project)

        return render(request,
            'project/result/%s.html' % template_name,
            {'project_result': project_result})

    elif template_name == "entity_result_details":
        project = get_object_or_404(Project, pk=project_id)
        project_result = Result.objects.filter(project=project)

        entity_result = []
        for item_result in project_result:
            username = item_result.user.name
            data_id = item_result.data.id
            result_json = json.loads(str(item_result.result))
            data_json = json.loads(str(item_result.data.json))["entities"]

            for i in range(len(result_json)):
                data_ith = data_json[i]
                entity_result.append(
                    {
                        "username": username,
                        "data_id": data_id,
                        "result": result_json[i],
                        "raw": data_ith["raw"],
                        "translation": data_ith["translation"]
                    })
        return render(request,
            'project/result/%s.html' % template_name,
            {'entity_result': entity_result})

    elif template_name == 'sentence_match_result_details':
        project = get_object_or_404(Project, pk=project_id)
        project_result = Result.objects.filter(project=project)

        sentences_result = []
        for item_result in project_result:
            username = item_result.user.name
            data_id = item_result.data.id
            result_json = json.loads(str(item_result.result))
            data_json = json.loads(str(item_result.data.json))["sentences"]

            for i in range(len(result_json)):
                data_ith = data_json[i]
                sentences_result.append(
                    {
                        "username": username,
                        "data_id": data_id,
                        "result": result_json[i],
                        "raw": data_ith["raw"],
                        "translation": data_ith["translation"]
                    })

        return render(request,
            'project/result/%s.html' % template_name,
            {'result': sentences_result})
    else:
        raise Http404("Unknow template for result_details page: %s" % template_name)


def project_answer(request, project_id, user_id, data_id):
    '''
    User's answer will be handled in this function.
    '''

    result_value = request.POST['result']
    comment = request.POST['comment']
    project = get_object_or_404(Project, pk=project_id)
    user = get_object_or_404(User, pk=user_id)
    data = get_object_or_404(Data, pk=data_id)
    result = Result.objects.raw(
        " select * from project_result where project_id = %s"
        " and user_id = %s and data_id = %s ", [str(project_id), str(user_id), str(data_id)]
    )[0]
    result.result = result_value
    result.comment = comment
    result.save()
    return redirect('project_task', project_id=project_id, user_id=user_id)


def project_new(request):
    '''
    To create a new project.
    '''
    if request.method == 'POST':
        name = request.POST['name']
        project_type = request.POST['project_type']
        result_details_view = request.POST['result_details_view']

        task_view_id = request.POST['task_view_id']
        task_view = None
        if not task_view_id:
            # TODO: add task view creation
            pass
        task_view = get_object_or_404(TaskView, pk=task_view_id)

        source_id = None
        source = None

        if "source_id" not in request.POST:
            source_name = request.POST['source_name']
            source = Source(name=source_name)
            source.save()
            data_file = request.FILES['file']
            for line in data_file:
                line = line.strip()
                if line:
                    data = Data(source=source, json=line)
                    data.save()
            source_id = source.id
        else:
            source_id = request.POST['source_id']
            source = get_object_or_404(Source, pk=source_id)

        users_id = request.POST.getlist('users')


        project = Project(
            name=name,
            project_type=project_type,
            task_view=task_view,
            result_details_view=result_details_view,
            source=source)
        project.save()

        for user_id in users_id:
            user = get_object_or_404(User, pk=user_id)
            project.users.add(user)

        if "source_id" not in request.POST and "dis_num" in request.POST:
            results_num_per_user = ceil(source.data_set.count() * int(request.POST["dis_num"]) / len(users_id))
            dis_num = int(request.POST["dis_num"])
            project.project_boundary = dis_num
            project.save()

            if dis_num >= len(users_id) and dis_num != 1:
                # TODO: add error page or pop up warning
                print('should not reach here')
                # return render_to_response('project_new', message="Invaild DISTRIBUTE number,"
                #                                                  " please be less than the number of users you choose")
            temp = {}

mysite/project/templates/polls/confirm.html
<p>you vote for: {{vote_item.trans_content}}</p>
<p>Proceeding to result page</p>
<script type="text/javascript">
    window.location.href = "/polls/result/{{vote_item.id}}";

</script>

mysite/project/templates/polls/download.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Download</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="panel panel-default col-md-8">
    <div class="panel-heading">批量生成BLEU分数</div>
    <div class="panel-body">
        <p><strong>上传文本类型为txt格式，请将每句各行显示，例如：</strong>
            <br>hello
            <br>right
            <br>...
        </p>
        <p><strong>上传的文本为两类：需要翻译的原句，用户提供的翻译，请在上传前选择翻译的源语言和目标语言</strong></p>
        <form method="post" enctype="multipart/form-data" id='upload_form'>
            {% csrf_token %}
            <div class="row">
                <label>原句文件</label>
                <input id="source_file" type="file" name="source_file" accept=".txt" required>
                <label>用户翻译文件</label>
                <input id="user_file" type="file" name="user_file" accept=".txt" required>
                <label>源语言：</label>
                <select class="selectpicker" name="lang" value="loadSelection('lang')" id="lang">
                    <option value="en">英文</option>
                    <option value="zh">中文</option>
                </select>
                <label>目标语言：</label>
                <select class="selectpicker" name="to" value="loadSelection('to')" id="to">
                    <option value="zh">中文</option>
                    <option value="en">英文</option>
                </select>
                <button class="btn btn-primary pull-right" type="submit">Submit your files</button>
                <br><label>类别：</label>
                <div class="checkbox">
                    <label>
                        <input id="tech" type="checkbox" name="technology" checked="checked">
                        科技
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input id="med" type="checkbox" name="medical" checked="checked">
                        医疗
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input id="pol" type="checkbox" name="political" checked="checked">
                        政治
                    </label>
                </div>

            </div>
        </form>
    </div>
    <div id="loadingdiv">{% load static %}
        <img src="{% static 'ajax-loader.gif' %}" class="img-responsive center-block">
        <p class="text-center">Analyzing...</p>
    </div>

    <div id="download_list">

    </div>
</div>

<a href="/polls/" class="pull-right">Go back transvote</a>
</body>
<script type="text/javascript">
        function loadSelection(target) {
            var list = document.getElementById(target);
            var index = list.selectedIndex;
            return select = list[index].text;
        }

</script>
<script type="text/javascript">
    $('#upload_form').on('submit', function(event){
        event.preventDefault();
        console.log('submit');
        // send_files();
        var this_master = $(this);

        this_master.find('input[type="checkbox"]').each( function () {
            var checkbox_this = $(this);


            if( checkbox_this.is(":checked") == true ) {
                checkbox_this.attr('value','1');
            } else {
                // checkbox_this.prop('checked',true);
                //DONT' ITS JUST CHECK THE CHECKBOX TO SUBMIT FORM DATA
                checkbox_this.attr('value','0');
            }
        })


        var formData = new FormData();
        formData.append('source_file', $('#source_file')[0].files[0]);
        formData.append('user_file', $('#user_file')[0].files[0]);
        formData.append('lang', $('#lang').val());
        formData.append('to', $('#to').val());
        formData.append('tech', $('#tech').val());
        formData.append('med', $('#med').val());
        formData.append('pol', $('#pol').val());
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        send_files(formData);
    });
    function send_files(formData) {
        $.ajax({
            url: "/polls/download/",
            type: "POST",
            contentType: false,
            processData: false,
            data: formData,
            success: function(data) {
                $('#download_list').html(data)
            }
        })
    }


</script>

<script>
    var $loading = $('#loadingdiv').hide();
    $(document)
        .ajaxStart(function(){
            $loading.show();
        })
        .ajaxStop(function(){
            $loading.hide();
        })
    ;

</script>
</html>

mysite/project/templates/polls/download_list.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li
            {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}


<table class="table">
    <thead>
    <tr>
        <th>翻译引擎</th>
        <th>分数结果文件</th>
        <th>翻译结果下载</th>
    </tr>
    </thead>
    <tbody>
    {% for each, value in download_links.items %}
    <tr>
        <td>{{each}}</td>
        <td>{{value.0}}</td>
        {% load static %}
        <td>{% load static %}<a href="{% static value.1 %}" download>Link</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

mysite/project/templates/polls/result.html
<!DOCTYPE html>
<html lang="zh-CN" class="gr__getbootstrap_com">
<head>
    <meta charset="UTF-8">
    <title>Vote Result</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5944c1871a01ca2f"></script>

</head>
<body>
<div class="col-md-9" role="main">
    <table class="table">
        <p class="lead text-center">In the result page for:</p>
        <p class="lead">
            <mark>{{ source }}</mark>
        </p>
        <div class="addthis_inline_share_toolbox"></div>
        <thread>
            <tr>
                <th>Engine</th>
                <th>翻译语句</th>
                <th>投票数目</th>
                <th>翻译时间</th>
            </tr>
            <tbody>
            {% for tran in all_trans_result.all %}

            {% for each in tran.transhistory_set.all %}
            <tr>
                <td>{{ tran.trans_engine }}</td>
                <td>{{ each.trans_content }}</td>
                <td>{{ each.vote_result }}</td>
                <td>{{ each.trans_time }}</td>
            </tr>
            {% endfor %}
            {% endfor %}
            </tbody>
        </thread>
    </table>

    <p><strong>Make comment:</strong></p>
    <div class="alert" id="status">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li
                    {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    {% if not_submitted %}
    <form id="comment_form" class="search-wraper" role="search" action="/result/{{ id }}/" method="POST">{% csrf_token %}

        <div class="form-group">
                <textarea id="comment_area" maxlength="3000" type="text" name="comment" class="form-control" rows=5
                          cols=20
                          placeholder="输入您对翻译结果的建议">{{ comment }}</textarea>
            <i class="fa x fa-search onX"></i>
        </div>
        <button type="submit" class="btn btn-success btn-circle btn-xl"><i class="glyphicon glyphicon-link"></i>Save
            comment
        </button>
    </form>
    {% endif %}
    <a href="/polls/">Go back to home</a>
</div>
</body>
</html>

mysite/project/templates/polls/search.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script type="text/javascript">
        function loadSelection(target) {
            var list = document.getElementById(target);
            var index = list.selectedIndex;
            return select = list[index].text;
        }
    </script>


    <script type="text/javascript">
      var datefield=document.createElement("input")
      datefield.setAttribute("type", "date")
      if (datefield.type!="date"){ //if browser doesn't support input type="date", load files for jQuery UI Date Picker
         document.write('<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />\n')
        document.write('<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"><\/script>\n')
        document.write('<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"><\/script>\n')
      }

    </script>
    <script>
        if (datefield.type!="date"){ //if browser doesn't support input type="date", initialize date picker widget:
           jQuery(function($){ //on document.ready
               $('#start_date').datepicker({ dateFormat: 'yy-mm-dd' });
               $('#end_date').datepicker({ dateFormat: 'yy-mm-dd' });
           })
        }

    </script>
</head>
<body id="main_body">
<div class="container">
    <div class="row">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">搜索</div>
                <div class="panel-body">
                    <form id="search_form" role="search" action="/search/" method="POST">{% csrf_token %}
                        <input type="hidden" name="contentCount" value="1"/>
                        <div class="form-group">
                            <label for="content-1">搜索engine(s)</label>
                            <select class="form-control" name="engine" value="loadSelection('engine')" id="engine">
                                <option value="google">Google</option>
                                <option value="baidu">百度</option>
                                <option value="youdao">有道</option>
                                <option value="bing">Bing</option>
                                <option value="atman">Atman</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="input-StartDate-1">启始时间</label>
                            <input id="start_date" type="date" class="form-control"
                                   name="start_time"
                                   value="{{start_time}}" required>
                        </div>

                        <div class="form-group">
                            <label for="input-EndDate-1">结束时间</label>
                            <input id="end_date" type="date" class="form-control" name="end_time"
                                   value="{{end_time}}" required>
                        </div>

                        <button type="submit" class="btn btn-default">搜索</button>
                        <a href="/" class="btn btn-default">回到翻译界面</a>
                    </form>
                </div><!-- END panel-body -->
            </div><!-- END panel -->
        </div><!-- END panel-group -->
    </div><!-- END row -->
</div><!-- END container -->

<div id="loadingdiv">{% load static %}
    <img src="{% static 'ajax-loader.gif' %}" class="img-responsive center-block">
    <p class="text-center">Searching...</p>
</div>
<div class="col-md-10 col-md-offset-1" id="show_search_results">
</div>


<script type="text/javascript">
        var curr_page = 1;
        $('#search_form').on('submit', function(event){
            event.preventDefault();
            console.log('form submit')
            change_page(curr_page);
        });
        $('.col-md-10').on("click", ".last_page", function(event) {
            event.preventDefault();
            curr_page -= 1;
            change_page(curr_page);
        });
        $('.col-md-10').on("click", ".next_page", function(event) {
            event.preventDefault();

            curr_page += 1;
            change_page(curr_page);
        });

        $('.col-md-10').on("click", ".first_page", function(event) {
            event.preventDefault();

            curr_page = 0;
            change_page(curr_page);
        });


        function change_page(page){
            $.ajax({
                url: "/polls/search/",
                type: "POST",
                data:{
                        'engine': $('#engine').val(),
                        'start_time': $('#start_date').val(),
                        'end_time': $('#end_date').val(),
                        'page': page,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(data) {
                    $('#show_search_results').html(data)
                }

            });
        }


</script>

<script>
    var $loading = $('#loadingdiv').hide();
    $(document)
        .ajaxStart(function(){
            $loading.show();
        })
        .ajaxStop(function(){
            $loading.hide();
        })
    ;

</script>
</body>
</html>